# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Open The Debate
tagline:          'America needs a real debate'
description:      'America needs a real debate'
url:              http://openthedebate.club
baseurl:          /

author:
  name:           'Open The Debate'
  url:            https://twitter.com/openthedebate

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/openthedebate/openthedebate.github.io
  
gems: [jekyll-paginate]
